# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import StandardScaler

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    Path("Resources/applicants_data.csv")
)
 
# Review the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Review the data types associated with the columns
list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

['NAME',
 'APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=["EIN","NAME"]).copy()

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables 
categorical_variables = ["APPLICATION_TYPE","AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION", "INCOME_AMT","SPECIAL_CONSIDERATIONS"]

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [7]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [8]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Review the DataFrame
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [9]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat(
    [
       applicant_data_df[['STATUS','ASK_AMT','IS_SUCCESSFUL']],
       encoded_df
    ],
    axis=1
)

# Review the Dataframe
encoded_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [10]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL'].values

# Display a sample of y
y[:5]

array([1, 1, 0, 1, 1], dtype=int64)

In [11]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=['IS_SUCCESSFUL']).values

# Review the features DataFrame
X

array([[1.0000000e+00, 5.0000000e+03, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.0859000e+05, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       ...,
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 3.6500179e+07, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00]])

### Step 6: Split the features and target sets into training and testing datasets.

In [12]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [58]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [111]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train[0])


# Review the number of features
number_input_features

116

In [112]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [113]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

2

In [114]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

2

In [115]:
# Create the Sequential model instance
nn = Sequential()

In [116]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1,input_dim=number_input_features, activation="relu"))

In [117]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [118]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [119]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 2)                 234

 dense_31 (Dense)            (None, 2)                 6

 dense_32 (Dense)            (None, 1)                 3

=================================================================
Total params: 243
Trainable params: 243
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [120]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [121]:
# Fit the model using 50 epochs and the training data
model=nn.fit(X, y, validation_split=0.3, epochs=50)

Epoch 1/50
751/751 [==============================] - 1s 1ms/step - loss: 0.6451 - accuracy: 0.6363 - val_loss: 0.6444 - val_accuracy: 0.6586
Epoch 2/50
751/751 [==============================] - 1s 933us/step - loss: 0.6040 - accuracy: 0.6904 - val_loss: 0.6266 - val_accuracy: 0.6755
Epoch 3/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5878 - accuracy: 0.7015 - val_loss: 0.6188 - val_accuracy: 0.6788
Epoch 4/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5810 - accuracy: 0.7016 - val_loss: 0.6149 - val_accuracy: 0.6775
Epoch 5/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5760 - accuracy: 0.7283 - val_loss: 0.6131 - val_accuracy: 0.6851
Epoch 6/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5720 - accuracy: 0.7378 - val_loss: 0.6124 - val_accuracy: 0.6868
Epoch 7/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5691 - accuracy: 0.7384 - val_loss: 0.6118 - val_accuracy: 0.6872
Epoch 8/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5671 - accuracy: 0.7385 - val_loss: 0.6139 - val_accuracy: 0.6873
Epoch 9/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5655 - accuracy: 0.7392 - val_loss: 0.6123 - val_accuracy: 0.6888
Epoch 10/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5643 - accuracy: 0.7398 - val_loss: 0.6137 - val_accuracy: 0.6889
Epoch 11/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5638 - accuracy: 0.7401 - val_loss: 0.6119 - val_accuracy: 0.6898
Epoch 12/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5635 - accuracy: 0.7392 - val_loss: 0.6127 - val_accuracy: 0.6899
Epoch 13/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5632 - accuracy: 0.7400 - val_loss: 0.6167 - val_accuracy: 0.6889
Epoch 14/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5632 - accuracy: 0.7401 - val_loss: 0.6131 - val_accuracy: 0.6903
Epoch 15/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5630 - accuracy: 0.7400 - val_loss: 0.6129 - val_accuracy: 0.6906
Epoch 16/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5628 - accuracy: 0.7402 - val_loss: 0.6134 - val_accuracy: 0.6907
Epoch 17/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5628 - accuracy: 0.7401 - val_loss: 0.6140 - val_accuracy: 0.6898
Epoch 18/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5627 - accuracy: 0.7403 - val_loss: 0.6124 - val_accuracy: 0.6906
Epoch 19/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5626 - accuracy: 0.7398 - val_loss: 0.6102 - val_accuracy: 0.6925
Epoch 20/50
751/751 [==============================] - 1s 943us/step - loss: 0.5620 - accuracy: 0.7410 - val_loss: 0.6125 - val_accuracy: 0.6916
Epoch 21/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5620 - accuracy: 0.7411 - val_loss: 0.6119 - val_accuracy: 0.6923
Epoch 22/50
751/751 [==============================] - 1s 961us/step - loss: 0.5618 - accuracy: 0.7411 - val_loss: 0.6131 - val_accuracy: 0.6921
Epoch 23/50
751/751 [==============================] - 1s 986us/step - loss: 0.5620 - accuracy: 0.7409 - val_loss: 0.6111 - val_accuracy: 0.6929
Epoch 24/50
751/751 [==============================] - 1s 965us/step - loss: 0.5619 - accuracy: 0.7412 - val_loss: 0.6119 - val_accuracy: 0.6924
Epoch 25/50
751/751 [==============================] - 1s 977us/step - loss: 0.5619 - accuracy: 0.7410 - val_loss: 0.6144 - val_accuracy: 0.6925
Epoch 26/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5619 - accuracy: 0.7413 - val_loss: 0.6147 - val_accuracy: 0.6912
Epoch 27/50
751/751 [==============================] - 1s 967us/step - loss: 0.5619 - accuracy: 0.7413 - val_loss: 0.6119 - val_accuracy: 0.6924
Epoch 28/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5616 - accuracy: 0.7416 - val_loss: 0.6130 - val_accuracy: 0.6927
Epoch 29/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5616 - accuracy: 0.7408 - val_loss: 0.6137 - val_accuracy: 0.6930
Epoch 30/50
751/751 [==============================] - 1s 996us/step - loss: 0.5616 - accuracy: 0.7413 - val_loss: 0.6147 - val_accuracy: 0.6917
Epoch 31/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7413 - val_loss: 0.6142 - val_accuracy: 0.6914
Epoch 32/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5616 - accuracy: 0.7403 - val_loss: 0.6126 - val_accuracy: 0.6914
Epoch 33/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5615 - accuracy: 0.7408 - val_loss: 0.6131 - val_accuracy: 0.6927
Epoch 34/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7411 - val_loss: 0.6135 - val_accuracy: 0.6916
Epoch 35/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5615 - accuracy: 0.7413 - val_loss: 0.6119 - val_accuracy: 0.6927
Epoch 36/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7413 - val_loss: 0.6112 - val_accuracy: 0.6924
Epoch 37/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7413 - val_loss: 0.6141 - val_accuracy: 0.6914
Epoch 38/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7410 - val_loss: 0.6114 - val_accuracy: 0.6917
Epoch 39/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5613 - accuracy: 0.7411 - val_loss: 0.6109 - val_accuracy: 0.6917
Epoch 40/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7405 - val_loss: 0.6118 - val_accuracy: 0.6914
Epoch 41/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7409 - val_loss: 0.6118 - val_accuracy: 0.6917
Epoch 42/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5613 - accuracy: 0.7405 - val_loss: 0.6144 - val_accuracy: 0.6921
Epoch 43/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5613 - accuracy: 0.7411 - val_loss: 0.6141 - val_accuracy: 0.6913
Epoch 44/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5613 - accuracy: 0.7406 - val_loss: 0.6106 - val_accuracy: 0.6922
Epoch 45/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7409 - val_loss: 0.6111 - val_accuracy: 0.6922
Epoch 46/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5613 - accuracy: 0.7410 - val_loss: 0.6124 - val_accuracy: 0.6921
Epoch 47/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7418 - val_loss: 0.6126 - val_accuracy: 0.6924
Epoch 48/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7412 - val_loss: 0.6118 - val_accuracy: 0.6924
Epoch 49/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5610 - accuracy: 0.7413 - val_loss: 0.6128 - val_accuracy: 0.6914
Epoch 50/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5609 - accuracy: 0.7412 - val_loss: 0.6111 - val_accuracy: 0.6923

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [122]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)


# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5763 - accuracy: 0.7278 - 137ms/epoch - 511us/step
Loss: 0.5762888789176941, Accuracy: 0.7278134226799011

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [123]:
# Set the model's file path
file_path = Path("../Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [127]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train[0])


# Review the number of features
number_input_features

116

In [129]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [131]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 4

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

4

In [132]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [133]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A1.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_33 (Dense)            (None, 2)                 234

 dense_34 (Dense)            (None, 1)                 3

=================================================================
Total params: 237
Trainable params: 237
Non-trainable params: 0
_________________________________________________________________

In [134]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [135]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 636us/step - loss: 0.6407 - accuracy: 0.6458
Epoch 2/50
804/804 [==============================] - 1s 651us/step - loss: 0.5870 - accuracy: 0.7079
Epoch 3/50
804/804 [==============================] - 1s 668us/step - loss: 0.5747 - accuracy: 0.7133
Epoch 4/50
804/804 [==============================] - 1s 649us/step - loss: 0.5674 - accuracy: 0.7138
Epoch 5/50
804/804 [==============================] - 1s 685us/step - loss: 0.5645 - accuracy: 0.7142
Epoch 6/50
804/804 [==============================] - 1s 689us/step - loss: 0.5639 - accuracy: 0.7163
Epoch 7/50
804/804 [==============================] - 1s 855us/step - loss: 0.5633 - accuracy: 0.7156
Epoch 8/50
804/804 [==============================] - 1s 836us/step - loss: 0.5628 - accuracy: 0.7171
Epoch 9/50
804/804 [==============================] - 1s 824us/step - loss: 0.5624 - accuracy: 0.7172
Epoch 10/50
804/804 [==============================] - 1s 863us/step - loss: 0.5624 - accuracy: 0.7175
Epoch 11/50
804/804 [==============================] - 1s 844us/step - loss: 0.5622 - accuracy: 0.7176
Epoch 12/50
804/804 [==============================] - 1s 830us/step - loss: 0.5622 - accuracy: 0.7163
Epoch 13/50
804/804 [==============================] - 1s 955us/step - loss: 0.5621 - accuracy: 0.7169
Epoch 14/50
804/804 [==============================] - 1s 929us/step - loss: 0.5622 - accuracy: 0.7172
Epoch 15/50
804/804 [==============================] - 1s 896us/step - loss: 0.5619 - accuracy: 0.7165
Epoch 16/50
804/804 [==============================] - 1s 856us/step - loss: 0.5620 - accuracy: 0.7171
Epoch 17/50
804/804 [==============================] - 1s 834us/step - loss: 0.5619 - accuracy: 0.7175
Epoch 18/50
804/804 [==============================] - 1s 853us/step - loss: 0.5619 - accuracy: 0.7172
Epoch 19/50
804/804 [==============================] - 1s 858us/step - loss: 0.5619 - accuracy: 0.7163
Epoch 20/50
804/804 [==============================] - 1s 852us/step - loss: 0.5619 - accuracy: 0.7177
Epoch 21/50
804/804 [==============================] - 1s 865us/step - loss: 0.5618 - accuracy: 0.7169
Epoch 22/50
804/804 [==============================] - 1s 843us/step - loss: 0.5618 - accuracy: 0.7167
Epoch 23/50
804/804 [==============================] - 1s 830us/step - loss: 0.5618 - accuracy: 0.7170
Epoch 24/50
804/804 [==============================] - 1s 864us/step - loss: 0.5617 - accuracy: 0.7173
Epoch 25/50
804/804 [==============================] - 1s 851us/step - loss: 0.5613 - accuracy: 0.7186
Epoch 26/50
804/804 [==============================] - 1s 820us/step - loss: 0.5608 - accuracy: 0.7193
Epoch 27/50
804/804 [==============================] - 1s 856us/step - loss: 0.5607 - accuracy: 0.7187
Epoch 28/50
804/804 [==============================] - 1s 786us/step - loss: 0.5607 - accuracy: 0.7192
Epoch 29/50
804/804 [==============================] - 1s 653us/step - loss: 0.5607 - accuracy: 0.7184
Epoch 30/50
804/804 [==============================] - 1s 679us/step - loss: 0.5608 - accuracy: 0.7187
Epoch 31/50
804/804 [==============================] - 1s 690us/step - loss: 0.5606 - accuracy: 0.7189
Epoch 32/50
804/804 [==============================] - 1s 681us/step - loss: 0.5607 - accuracy: 0.7193
Epoch 33/50
804/804 [==============================] - 1s 723us/step - loss: 0.5605 - accuracy: 0.7192
Epoch 34/50
804/804 [==============================] - 1s 828us/step - loss: 0.5605 - accuracy: 0.7186
Epoch 35/50
804/804 [==============================] - 1s 763us/step - loss: 0.5606 - accuracy: 0.7196
Epoch 36/50
804/804 [==============================] - 1s 669us/step - loss: 0.5605 - accuracy: 0.7187
Epoch 37/50
804/804 [==============================] - 1s 681us/step - loss: 0.5605 - accuracy: 0.7199
Epoch 38/50
804/804 [==============================] - 1s 687us/step - loss: 0.5605 - accuracy: 0.7196
Epoch 39/50
804/804 [==============================] - 1s 694us/step - loss: 0.5605 - accuracy: 0.7191
Epoch 40/50
804/804 [==============================] - 1s 745us/step - loss: 0.5605 - accuracy: 0.7198
Epoch 41/50
804/804 [==============================] - 1s 992us/step - loss: 0.5606 - accuracy: 0.7193
Epoch 42/50
804/804 [==============================] - 1s 997us/step - loss: 0.5604 - accuracy: 0.7185
Epoch 43/50
804/804 [==============================] - 1s 885us/step - loss: 0.5604 - accuracy: 0.7199
Epoch 44/50
804/804 [==============================] - 1s 991us/step - loss: 0.5603 - accuracy: 0.7191
Epoch 45/50
804/804 [==============================] - 1s 961us/step - loss: 0.5601 - accuracy: 0.7194
Epoch 46/50
804/804 [==============================] - 1s 951us/step - loss: 0.5596 - accuracy: 0.7195
Epoch 47/50
804/804 [==============================] - 1s 963us/step - loss: 0.5592 - accuracy: 0.7196
Epoch 48/50
804/804 [==============================] - 1s 907us/step - loss: 0.5589 - accuracy: 0.7191
Epoch 49/50
804/804 [==============================] - 1s 950us/step - loss: 0.5586 - accuracy: 0.7189
Epoch 50/50
804/804 [==============================] - 1s 905us/step - loss: 0.5583 - accuracy: 0.7190

#### Alternative Model 2

In [145]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train[0])

# Review the number of features
number_input_features

116

In [146]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [147]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (hidden_nodes_layer1 + 1) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

1

In [148]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [149]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A2.add(Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_37 (Dense)            (None, 2)                 234

 dense_38 (Dense)            (None, 1)                 3

=================================================================
Total params: 237
Trainable params: 237
Non-trainable params: 0
_________________________________________________________________

In [150]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [151]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 639us/step - loss: 0.6655 - accuracy: 0.6621
Epoch 2/100
804/804 [==============================] - 1s 646us/step - loss: 0.6100 - accuracy: 0.7138
Epoch 3/100
804/804 [==============================] - 1s 669us/step - loss: 0.5945 - accuracy: 0.7173
Epoch 4/100
804/804 [==============================] - 1s 706us/step - loss: 0.5810 - accuracy: 0.7278
Epoch 5/100
804/804 [==============================] - 1s 832us/step - loss: 0.5762 - accuracy: 0.7279
Epoch 6/100
804/804 [==============================] - 1s 841us/step - loss: 0.5742 - accuracy: 0.7282
Epoch 7/100
804/804 [==============================] - 1s 854us/step - loss: 0.5715 - accuracy: 0.7282
Epoch 8/100
804/804 [==============================] - 1s 816us/step - loss: 0.5697 - accuracy: 0.7285
Epoch 9/100
804/804 [==============================] - 1s 862us/step - loss: 0.5663 - accuracy: 0.7269
Epoch 10/100
804/804 [==============================] - 1s 859us/step - loss: 0.5635 - accuracy: 0.7271
Epoch 11/100
804/804 [==============================] - 1s 816us/step - loss: 0.5623 - accuracy: 0.7269
Epoch 12/100
804/804 [==============================] - 1s 923us/step - loss: 0.5610 - accuracy: 0.7256
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5606 - accuracy: 0.7264
Epoch 14/100
804/804 [==============================] - 1s 936us/step - loss: 0.5600 - accuracy: 0.7271
Epoch 15/100
804/804 [==============================] - 1s 847us/step - loss: 0.5597 - accuracy: 0.7262
Epoch 16/100
804/804 [==============================] - 1s 838us/step - loss: 0.5596 - accuracy: 0.7261
Epoch 17/100
804/804 [==============================] - 1s 827us/step - loss: 0.5592 - accuracy: 0.7274
Epoch 18/100
804/804 [==============================] - 1s 848us/step - loss: 0.5591 - accuracy: 0.7268
Epoch 19/100
804/804 [==============================] - 1s 837us/step - loss: 0.5588 - accuracy: 0.7268
Epoch 20/100
804/804 [==============================] - 1s 835us/step - loss: 0.5587 - accuracy: 0.7271
Epoch 21/100
804/804 [==============================] - 1s 877us/step - loss: 0.5587 - accuracy: 0.7255
Epoch 22/100
804/804 [==============================] - 1s 841us/step - loss: 0.5587 - accuracy: 0.7258
Epoch 23/100
804/804 [==============================] - 1s 840us/step - loss: 0.5588 - accuracy: 0.7271
Epoch 24/100
804/804 [==============================] - 1s 964us/step - loss: 0.5586 - accuracy: 0.7263
Epoch 25/100
804/804 [==============================] - 1s 859us/step - loss: 0.5585 - accuracy: 0.7271
Epoch 26/100
804/804 [==============================] - 1s 770us/step - loss: 0.5584 - accuracy: 0.7262
Epoch 27/100
804/804 [==============================] - 1s 684us/step - loss: 0.5584 - accuracy: 0.7257
Epoch 28/100
804/804 [==============================] - 1s 678us/step - loss: 0.5584 - accuracy: 0.7266
Epoch 29/100
804/804 [==============================] - 1s 674us/step - loss: 0.5583 - accuracy: 0.7260
Epoch 30/100
804/804 [==============================] - 1s 698us/step - loss: 0.5582 - accuracy: 0.7268
Epoch 31/100
804/804 [==============================] - 1s 687us/step - loss: 0.5583 - accuracy: 0.7256
Epoch 32/100
804/804 [==============================] - 1s 665us/step - loss: 0.5581 - accuracy: 0.7259
Epoch 33/100
804/804 [==============================] - 1s 711us/step - loss: 0.5582 - accuracy: 0.7264
Epoch 34/100
804/804 [==============================] - 1s 704us/step - loss: 0.5581 - accuracy: 0.7275
Epoch 35/100
804/804 [==============================] - 1s 714us/step - loss: 0.5582 - accuracy: 0.7265
Epoch 36/100
804/804 [==============================] - 1s 695us/step - loss: 0.5582 - accuracy: 0.7260
Epoch 37/100
804/804 [==============================] - 1s 726us/step - loss: 0.5580 - accuracy: 0.7262
Epoch 38/100
804/804 [==============================] - 1s 733us/step - loss: 0.5580 - accuracy: 0.7269
Epoch 39/100
804/804 [==============================] - 1s 699us/step - loss: 0.5582 - accuracy: 0.7279
Epoch 40/100
804/804 [==============================] - 1s 729us/step - loss: 0.5580 - accuracy: 0.7268
Epoch 41/100
804/804 [==============================] - 1s 805us/step - loss: 0.5579 - accuracy: 0.7267
Epoch 42/100
804/804 [==============================] - 1s 956us/step - loss: 0.5578 - accuracy: 0.7265
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5579 - accuracy: 0.7264
Epoch 44/100
804/804 [==============================] - 1s 977us/step - loss: 0.5579 - accuracy: 0.7274
Epoch 45/100
804/804 [==============================] - 1s 949us/step - loss: 0.5580 - accuracy: 0.7267
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5581 - accuracy: 0.7269
Epoch 47/100
804/804 [==============================] - 1s 937us/step - loss: 0.5580 - accuracy: 0.7265
Epoch 48/100
804/804 [==============================] - 1s 960us/step - loss: 0.5579 - accuracy: 0.7261
Epoch 49/100
804/804 [==============================] - 1s 946us/step - loss: 0.5580 - accuracy: 0.7268
Epoch 50/100
804/804 [==============================] - 1s 929us/step - loss: 0.5580 - accuracy: 0.7271
Epoch 51/100
804/804 [==============================] - 1s 957us/step - loss: 0.5579 - accuracy: 0.7271
Epoch 52/100
804/804 [==============================] - 1s 935us/step - loss: 0.5581 - accuracy: 0.7263
Epoch 53/100
804/804 [==============================] - 1s 925us/step - loss: 0.5580 - accuracy: 0.7271
Epoch 54/100
804/804 [==============================] - 1s 950us/step - loss: 0.5578 - accuracy: 0.7268
Epoch 55/100
804/804 [==============================] - 1s 937us/step - loss: 0.5580 - accuracy: 0.7261
Epoch 56/100
804/804 [==============================] - 1s 937us/step - loss: 0.5579 - accuracy: 0.7257
Epoch 57/100
804/804 [==============================] - 1s 936us/step - loss: 0.5578 - accuracy: 0.7270
Epoch 58/100
804/804 [==============================] - 1s 924us/step - loss: 0.5579 - accuracy: 0.7261
Epoch 59/100
804/804 [==============================] - 1s 938us/step - loss: 0.5580 - accuracy: 0.7269
Epoch 60/100
804/804 [==============================] - 1s 934us/step - loss: 0.5578 - accuracy: 0.7275
Epoch 61/100
804/804 [==============================] - 1s 938us/step - loss: 0.5578 - accuracy: 0.7266
Epoch 62/100
804/804 [==============================] - 1s 973us/step - loss: 0.5579 - accuracy: 0.7270
Epoch 63/100
804/804 [==============================] - 1s 935us/step - loss: 0.5578 - accuracy: 0.7275
Epoch 64/100
804/804 [==============================] - 1s 936us/step - loss: 0.5579 - accuracy: 0.7260
Epoch 65/100
804/804 [==============================] - 1s 964us/step - loss: 0.5579 - accuracy: 0.7260
Epoch 66/100
804/804 [==============================] - 1s 920us/step - loss: 0.5579 - accuracy: 0.7269
Epoch 67/100
804/804 [==============================] - 1s 937us/step - loss: 0.5577 - accuracy: 0.7267
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5576 - accuracy: 0.7256
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5579 - accuracy: 0.7267
Epoch 70/100
804/804 [==============================] - 1s 889us/step - loss: 0.5578 - accuracy: 0.7263
Epoch 71/100
804/804 [==============================] - 1s 919us/step - loss: 0.5579 - accuracy: 0.7265
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7270
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5578 - accuracy: 0.7269
Epoch 74/100
804/804 [==============================] - 1s 978us/step - loss: 0.5577 - accuracy: 0.7265
Epoch 75/100
804/804 [==============================] - 1s 980us/step - loss: 0.5578 - accuracy: 0.7272
Epoch 76/100
804/804 [==============================] - 1s 931us/step - loss: 0.5577 - accuracy: 0.7264
Epoch 77/100
804/804 [==============================] - 1s 945us/step - loss: 0.5577 - accuracy: 0.7270
Epoch 78/100
804/804 [==============================] - 1s 940us/step - loss: 0.5578 - accuracy: 0.7264
Epoch 79/100
804/804 [==============================] - 1s 947us/step - loss: 0.5577 - accuracy: 0.7261
Epoch 80/100
804/804 [==============================] - 1s 938us/step - loss: 0.5577 - accuracy: 0.7261
Epoch 81/100
804/804 [==============================] - 1s 938us/step - loss: 0.5578 - accuracy: 0.7263
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7272
Epoch 83/100
804/804 [==============================] - 1s 947us/step - loss: 0.5577 - accuracy: 0.7271
Epoch 84/100
804/804 [==============================] - 1s 941us/step - loss: 0.5577 - accuracy: 0.7264
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5578 - accuracy: 0.7265
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5576 - accuracy: 0.7266
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.7268
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5576 - accuracy: 0.7267
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5578 - accuracy: 0.7269
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.7272
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.7268
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7270
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7271
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.7271
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7273
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.7274
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7269
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7266
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.7266
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5578 - accuracy: 0.7270

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [152]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5763 - accuracy: 0.7278 - 179ms/epoch - 666us/step
Loss: 0.5762888789176941, Accuracy: 0.7278134226799011

In [154]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =nn_A2.evaluate(X_test_scaled,y_test,verbose=2)


# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5624 - accuracy: 0.7279 - 217ms/epoch - 810us/step
Loss: 0.5623714327812195, Accuracy: 0.7279300093650818

In [156]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5624 - accuracy: 0.7279 - 138ms/epoch - 516us/step
Loss: 0.5623714327812195, Accuracy: 0.7279300093650818

### Step 3: Save each of your alternative models as an HDF5 file.

In [160]:
# Set the file path for the first alternative model
file_path = Path("../Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [161]:
# Set the file path for the second alternative model
file_path = Path("../Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)